alter table GARANT_CREDIT_ORDER add constraint FK_GARANT_CREDIT_ORDER_ON_CONTRACTOR foreign key (CONTRACTOR_ID) references DF_CONTRACTOR(CORRESPONDENT_ID);
create index IDX_GARANT_CREDIT_ORDER_ON_CONTRACTOR on GARANT_CREDIT_ORDER (CONTRACTOR_ID);
