-- begin GARANT_CREDIT
alter table GARANT_CREDIT add constraint FK_GARANT_CREDIT_ON_CREDIT_TYPE foreign key (CREDIT_TYPE_ID) references GARANT_CREDIT_TYPE(ID)^
alter table GARANT_CREDIT add constraint FK_GARANT_CREDIT_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
alter table GARANT_CREDIT add constraint FK_GARANT_CREDIT_ON_BANK foreign key (BANK_ID) references DF_BANK(ID)^
alter table GARANT_CREDIT add constraint FK_GARANT_CREDIT_ON_TARGET foreign key (TARGET_ID) references GARANT_TARGET(ID)^
create index IDX_GARANT_CREDIT_ON_CREDIT_TYPE on GARANT_CREDIT (CREDIT_TYPE_ID)^
create index IDX_GARANT_CREDIT_ON_MANAGER on GARANT_CREDIT (MANAGER_ID)^
create index IDX_GARANT_CREDIT_ON_BANK on GARANT_CREDIT (BANK_ID)^
create index IDX_GARANT_CREDIT_ON_TARGET on GARANT_CREDIT (TARGET_ID)^
-- end GARANT_CREDIT
-- begin GARANT_TARGET
create unique index IDX_GARANT_TARGET_UK_NAME on GARANT_TARGET (NAME) where DELETE_TS is null ^
create unique index IDX_GARANT_TARGET_UK_CODE on GARANT_TARGET (CODE) where DELETE_TS is null ^
-- end GARANT_TARGET
-- begin GARANT_CREDIT_ORDER
alter table GARANT_CREDIT_ORDER add constraint FK_GARANT_CREDIT_ORDER_ON_CREDIT foreign key (CREDIT_ID) references GARANT_CREDIT(ID)^
alter table GARANT_CREDIT_ORDER add constraint FK_GARANT_CREDIT_ORDER_ON_CONTRACTOR foreign key (CONTRACTOR_ID) references DF_CONTRACTOR(CORRESPONDENT_ID)^
alter table GARANT_CREDIT_ORDER add constraint FK_GARANT_CREDIT_ORDER_ON_ID foreign key (ID) references WF_CARD(ID) on delete CASCADE^
create index IDX_GARANT_CREDIT_ORDER_ON_CREDIT on GARANT_CREDIT_ORDER (CREDIT_ID)^
create index IDX_GARANT_CREDIT_ORDER_ON_CONTRACTOR on GARANT_CREDIT_ORDER (CONTRACTOR_ID)^
-- end GARANT_CREDIT_ORDER
-- begin TM_TASK
alter table TM_TASK add constraint FK_TM_TASK_ON_CREDIT_ORDER foreign key (CREDIT_ORDER_ID) references GARANT_CREDIT_ORDER(ID)^
create index IDX_TM_TASK_ON_CREDIT_ORDER on TM_TASK (CREDIT_ORDER_ID)^
-- end TM_TASK
-- begin GARANT_EXT_CONTRACTOR
alter table GARANT_EXT_CONTRACTOR add constraint FK_GARANT_EXT_CONTRACTOR_ON_CONTRACTOR foreign key (CONTRACTOR_ID) references DF_CORRESPONDENT(ID) on delete CASCADE^
-- end GARANT_EXT_CONTRACTOR
